news_sites:
  eltiempo:
    url: http://eltiempo.com/
    queries:
      homepage_article_links: '.title-container a'
      article_body: '.articulo-contenido'
      article_title: '.titulo h1'
  eluniversal:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.field-content a'
      article_body: '.field-name-body'
      article_title: '.pane-content h1'
  elpais:
    url: https://www.elpais.com
    queries:
      homepage_article_links: '.headline a'
      article_body: '.article_body'
      article_title: '.article-header h1'